name: WYLA
version: 1.0.1
main: dev.xeaf.wyla.WYLA
description: "See \"What You're Looking At\" without a client side mod"
author: devdere
api-version: '1.21'
folia-supported: true

commands:
  wyla:
    description: "Enable or disable WYLA for yourself"
    usage: "/wyla"
    permission: wyla.command
    permission-message: "You do not have permission to use this command."

permissions:
  wyla.command:
    default: true